#!/usr/bin/env ruby

require 'optparse'
require "petrinet"

options = { transitions: [] }
OptionParser.new do |opts|
  opts.banner = "Usage: petrinet [options]"

  opts.on("-t", "--transition=TRANSITION", "Specify a transition to fire. Can be specified multiple times.") do |t|
    options[:transitions] << t.to_sym
  end

  opts.on("-o", "--output=PATH", "Where to write the animated gif") do |o|
    options[:output] = o
  end

  opts.on("-s", "--script=SCRIPT", "Specify a script file") do |o|
    options[:script] = o
  end
end.parse!

pnml = ARGV[0]
net = Petrinet::Net.from_pnml(IO.read(pnml))
transitions = options[:transitions]
output = options[:output]
if options[:script]
  script = Petrinet::MarkingTransitionScript.new(IO.read(options[:script]))
  net = net.mark(script.marking)
  transitions = script.transitions + transitions
  output ||= options[:script].gsub(/\.txt$/, '.gif')
end
net.to_animated_gif(transitions, output)
