#!/usr/bin/env ruby

require 'optparse'
require "petrinet"

options = { transitions: [] }
OptionParser.new do |opts|
  opts.banner = "Usage: petrinet [options]"

  opts.on("-t", "--transition=TRANSITION", "Specify a transition to fire. Can be specified multiple times.") do |t|
    options[:transitions] << t.to_sym
  end

  opts.on("-o", "--output=PATH", "Specify a file or directory to write the SVG(s)") do |o|
    options[:output] = o
  end
end.parse!

pnml = ARGV[0]
net = Petrinet::Net.from_pnml(IO.read(pnml))
net.to_animated_gif(options[:transitions], options[:output])
